### ISSUE TITLE
Including <glbinding\Binding.h> from a dll causes warnings

### ISSUE THREAD

**Issue by pouljin** [cginternals/glbinding#102]
Perhaps I'm doing something wrong, but when I attempt to include <glbinding\Binding.h> from a dll I get countless dll export warnings related to the standard template. I suppose I can export every single stl function to avoid this, but it seems like something that should be handled by a wrapper class inside of the glBinding code. Thoughts?

warning C4251: 'glbinding::FunctionCall::parameters' : class 'std::vector<glbinding::AbstractValue *,std::allocator<_Ty>>' needs to have dll-interface to be used by clients of struct 'glbinding::FunctionCall'	c:\Program Files (x86)\Microsoft Visual Studio 12.0\vc\include\glbinding64\glbinding\callbacks.h	31

**Comment by scheibel** [comment]
Unfortunately, this warning is slightly serious but we disabled it in all our projects. This should help you, too.

Normally, it is discouraged to export stl classes in the public interface due to the template instantiation problems when using even minimally different standard libraries. We "solve" this issue by requiring the same compiler and STL for all compiled artifacts.

**Comment by pouljin** [comment]
Yes, unfortunately for what I'm doing that won't always be the case that the dll and the executable calling it will be compiled on the same compilers. Which leaves me with the choice of exporting every STL template in the correct order in my program or adding an additional wrapper layer.

**Comment by scheibel** [comment]
We're currently examining a cross-platform solution. Our current approach (this seems equal to yours) with exporting templates doesn't work in GCC.

**Comment by pouljin** [comment]
Good to know. I think a wrapper class might be the way to go then.

**Comment by cgcostume** [comment]
Hi, @pouljin thanks for the remark. msvc warns you about mixing up stl binaries of different redistributables/compilers (since they are incompatible). If the warning is noted (done for glbinding) - and we explicitly decided to use stl in our api :smile:, i suggest to disable this specific warning either in your project or whenever you include glbinding headers (you can use ```/wd4251``` for this - we also did this (see ```PlatformWindowsMSVC.cmake```).

closing the issue for now.

**Comment by JPGygax68** [comment]
Has it ever been considered to try implementing this library header-only?

**Comment by scheibel** [comment]
The first versions were close to header-only but the compile time of dependent projects was too high so we switched approaches.
