### ISSUE TITLE
Solution file error MSB5004: The solution file has two projects named "ALL_BUILD"

### ISSUE THREAD

**Issue by j-o** [cginternals/glbinding#130]
Using CMake 3.4.1 and Visual Studio 2015 Update 1 produces the error above when opening the solution or building via MSBuild.

**Comment by j-o** [comment]
And was it intentional to re-enabled those thousands of dll interface warnings?

**Comment by sbusch42** [comment]
Those seem like two different issues.
1) Please try disabling the tests. Does this problem still occur? (if it doesn't, it might be due to the nested project in gmock/gtest)
2) Please provide a patch (in cmake-init) to disable that, after that we can update all projects

**Comment by j-o** [comment]
1) Yes, disabling the tests works. Oddly, I can build cmake-init and libzeug fine with tests enabled, glbinding, globjects and gloperate fail.
2) Will do that

**Comment by sbusch42** [comment]
2) done (thank you!)
1) This is really strange. What I've find out so far: if you remove the deploy-directory from being included, the problem disappears. So, some cmake option within the deploy/package-project must cause googlemock/googletest/gmock/ALL_BUILD.vcproj to be included in the main solution file. However, I wasn't able to identify the problem in the package project - it is nearly identical to the one in cmake-init. Maybe someone else finds the problem here ...

**Comment by sbusch42** [comment]
The problem here was the dependency from the pack-project to ALL_BUILD that has been added manually. I removed that for now, so now the project needs to be built before invoking the pack-target, at least with MSVC. If we don't want that, we should add our own top-level target and make it depend on all targets that need to be built.
