### ISSUE TITLE
CMake 3.2 Requirement Workaround

### ISSUE THREAD

**Issue by shehzan10** [cginternals/glbinding#147]
A lot of linux distributions do not support 3.2 in their package managers. Upcoming distributions like Ubuntu 16.04 are shipping with 3.3.2, but existing distributions such as Debian 8.2 (ships with 3.0.2), CentOS 7 etc still lag behind with older versions.

From what I have noticed, `WRITE_COMPILER_DETECTION_HEADER` is the only function that requires > 3.1.3. I think everything else is satisfied by 3.0.

Is there any chance that a workaround for this function can be provided?

I tried manually including the [WriteCompilerDetectionHeader](https://github.com/Kitware/CMake/blob/master/Modules/WriteCompilerDetectionHeader.cmake) in the cmake directory and include it from there. But unfortunately, it looks like the `get_property` for `CMAKE_${_lang}_KNOWN_FEATURES` is unsupported in 3.0.2. So the cxx_thread_local feature fails. So this is not an avenue that can be taken.

**Comment by cgcostume** [comment]
Thanks for reporting, this will be addressed in the next days for glbinding 2.0 release.

**Comment by scheibel** [comment]
I hope https://github.com/cginternals/glbinding/commit/f8c23d576c8c29d9c434986fef5178e8a61a5fef will do the trick, although testing with an actual cmake <3.2 system is pending.

**Comment by shehzan10** [comment]
I'll test it out as well.

**Comment by shehzan10** [comment]
I tried building the library, getting a lot of errors where `GLtype`, where type is int, float, enum etc `is not a class or namespace` or `not a member or 'gl' namespace`.
Looks like there are other errors with respect to C++11 too. Might pertain to missing `-std=c++11` compiler flag.

Selective output: I've added a build job on our CI server. You can see the output [here](http://ci.arrayfire.org/view/All/job/other/job/glbinding-linux/1/console).
GCC 4.9.2 and CMake 3.0.2.

**Comment by shehzan10** [comment]
Yeah looks like adding `-std=c++11` did the trick. I added it under the GCC/Clang condition in cmake/CompileOptions.cmake to test it out.
The glbinding-test also passed.

**Comment by scheibel** [comment]
Actually, the appropriate C++11 flag should be set using the following lines of the same file:
```cmake
set(DEFAULT_PROJECT_OPTIONS
    DEBUG_POSTFIX             "d"
    CXX_STANDARD              11
    LINKER_LANGUAGE           "CXX"
    POSITION_INDEPENDENT_CODE ON
    CXX_VISIBILITY_PRESET     "hidden"
)
```
Maybe there is some other issue that these options are ignored.

**Comment by shehzan10** [comment]
Yes I saw that and it does seem to be ignored. Probably stemming from the fact that CXX_STANDARD options was added in [CMake 3.1](https://cmake.org/cmake/help/v3.1/release/3.1.0.html). So it won't work with 3.0.

**Comment by scheibel** [comment]
@sbusch42 What is your opinion on that? I provided a solution that the required cmake 3.2 is relaxed to 3.1 because it was only required by the feature detection header generation. But a further relaxation to 3.0 would be desired as it wouldn't require a custom cmake on several linux systems.
Unfortunately, the ```CXX_STANDARD``` is only available with 3.1 or higher, for which I don't know any workaround besides the former solution in cmake-init 1.0.

**Comment by shehzan10** [comment]
This is what we do in our libraries:
```
IF(UNIX)
    ADD_DEFINITIONS(-std=c++11)
ENDIF(UNIX)
```
We generally cater to GCC/ICC/Clang so this is sufficient. I'm not sure if there are other UNIX compilers that don't support this flag.

I think this is a simple enough fix that can go in conjunction with the CXX_STANDARD option. Having them be redundant shouldn't make a difference IMO.

I think its a simple enough fix not to warrant an minimum version upgrade on the CMake front.

**Comment by sbusch42** [comment]
I'm sorry but I now object against the "simple enough fix" notion.

The whole point was to clean up the cmake code and use modern cmake features in order to get rid of all the clutter and inconsistencies that was necessary in old cmake code. Modern cmake has been cleaned up a lot so it's now possible to write much cleaner cmake code. If we now have to go back to the old ways, the whole point of the rewrite is lost.

The c++11 flag is a very good example because it is exactly not that simple. Depending on the compiler, it might be either "-std=c++0x" or "-std=gnu++0x", or some other variations which I am not able to recall right now. That is exactly what the new cmake standard property abstracts for us. So we would end up having to check the gcc version and if the else blocks to support different compiler versions - which is a perfect example of the clutter we wanted to get rid of.

So it's not "an easy enough fix" but would lead us right back to the mess we came from :(

I'm not saying that we cannot make some compromise here, but I think we must be very careful not to abandon the whole benefit we aimed at.

**Comment by shehzan10** [comment]
Sure, fair enough. All I'm suggesting is that there are ways to get around it without requiring a minimum version upgrade.

And just for the record, I do really appreciate the minimum version drop. It helps a lot of other projects from having to bump up their own versions.

I'll leave it to you guys to decide the course of action.

**Comment by scheibel** [comment]
Maybe you want to have another look at our soon-to-be-merged branch https://github.com/cginternals/glbinding/tree/glbinding-2.0-release. With the latest commits I added logic for a C++11 command line flag fallback as you suggested.
As we want to support all compilers matching MSVC >=2013 (Update 3), Clang >=3.3 and GCC>=4.8, we only have to add a ```-std=c++11``` flag for the GCC and Clang compilers (fortunately supported by all required versions).

Hopefully, glbinding should work with CMake 3.0 then. Please test.

**Comment by shehzan10** [comment]
Checked and looks good. [Log](http://ci.arrayfire.org/view/All/job/other/job/glbinding-linux/3/console) for your reference.

Just one comment, unless there is something I'm missing, from commit d9645b6, the version in this line `$<$<VERSION_LESS:${CMAKE_VERSION},3.2>` can be **3.1**. I believe CXX_STANDARD was added in 3.1. That said, I have not had a chance to test it directly with CMake 3.1. Let me know if you want me to test that out.

**Comment by scheibel** [comment]
We adapted the comparison against CMake 3.1 and pushed everything to the master branch (tested).
Thanks for the involvement and participation.

**Comment by shehzan10** [comment]
:+1: Thanks for working on the refactor!
