### ISSUE TITLE
logging.cpp doesn't compile.

### ISSUE THREAD

**Issue by Cthutu** [cginternals/glbinding#157]
When compiling logging.cpp for Win32 I get this error:

c:\program files (x86)\microsoft visual studio 12.0\vc\include\concrt.h(4774): error C3861: '__uncaught_exception': identifier not found

To fix this I added

`#include <eh.h>`

to the top.  I am not sure why it occurred yet but there is a build configuration that for some reason causes __uncaught_exception not to be defined.

**Comment by scheibel** [comment]
Thanks for reporting this strange compilation issue. It hasn't occurred even once until now.
You seem to use MSVC 2013 (Visual Studio 12). Which update do you have installed for this compiler/IDE?

**Comment by Cthutu** [comment]
I am up to update 5.  Strange thing is that I've used it in another MSVC
2013 project and it didn't occur.  Not sure what is triggering it.  Maybe
eh.h is included somewhere very indirectly elsewhere but I don't see how
yet.

**Comment by scheibel** [comment]
Okay, I think our setups include MSVC 2013 Update 3 and Update 4, but not Update 5. We will set up a system with Update 5 and see what happens.

**Comment by Cthutu** [comment]
Eek, I hope that's the problem after going to all that trouble.

**Comment by Cthutu** [comment]
I do have these extra compiler options: "/Gy /MP /EHsc /Zm225" that I
didn't have when I had a project that compiler.  I suspect /EHsc may have
something to do with this.

**Comment by Cthutu** [comment]
I tried removing /EHsc but that didn't change anything.

**Comment by Cthutu** [comment]
I've discovered exactly what is causing the problem.  In the project that fails, we define _HAS_EXCEPTIONS=0.  I suspect this is a Microsoft header problem and not a glbinding problem.  I think that in that situation "eh.h" needs to be included.

**Comment by cgcostume** [comment]
We are going to disable exceptions for glbinding with the next minor release.

**Comment by cgcostume** [comment]
@Cthutu thanks for you feedback, we just disabled exceptions for the glbinding library for MSVC (not for utils, examples, etc) and used the mentioned exception flag for the STL as well.

**Comment by cgcostume** [comment]
hmm, we just found out that in visual studio 2013 this workaround is not supported and reverted it.

Seem like the stl is not supposed to be used without exceptions (in msvc at least): 
https://connect.microsoft.com/VisualStudio/feedback/details/811347/compiling-vc-12-0-with-has-exceptions-0-and-including-concrt-h-causes-a-compiler-error

Furthermore, the used ```_HAS_EXCEPTIONS=0``` is not officially supported.

Since we mostly strive for exception free programming, we just reevaluated our reasoning here.
https://www.quora.com/Why-do-some-people-recommend-not-using-exception-handling-in-C%2B%2B/answer/Brian-Bi?srid=VmyS 

Even though glbinding would not benefit directly by using exceptions, the overhead seems negligible and the overall compatibility with other C++ projects probably increases.

@Cthutu, if the support for MSVC 2015 is sufficient for your project and exceptions will remain a no-go in, please refer to the commit 8addf6e2be1103727b170a69e1453064189a008b
