### ISSUE TITLE
Add debug dll / library to package

### ISSUE THREAD

**Issue by rggjan** [cginternals/glbinding#168]
From what I understand [here](http://stackoverflow.com/a/29506355/369009), it is only safe to ignore the warnings of [Ticket 141](https://github.com/cginternals/glbinding/issues/141) when both the application and the library (in this case glbinding) dll were compiled in debug or release mode.

It would be good to make it possible to compile, package and also link to (using the CMake scripts) the debug version of the dll.

**Comment by scheibel** [comment]
The linking using the ```glbinding-config.cmake``` script maintained and deployed by us already is aware of release and debug builds.
Generally, building zip archives and installer using both a release and debug build is possible but I don't know of a non-hacky CMake-only way to do so.

We will discuss about this issue.

**Comment by rggjan** [comment]
I see. So how can I get a package with debug and release dlls and libs? Just compile and pack the release version, and copy the (separately compiled) debug dll and lib by hand into the same package?

**Comment by cgcostume** [comment]
Yes, that would be a valid way. You could of course use CMake to do this somehow, but as @scheibel suggested, this always results in some hack, since CMake currently cannot differentiate the build configuration when packaging/installing. FYI, the branch [v2.0.0-installer](https://github.com/cginternals/glbinding/tree/v2.0.0-installer) contains some hacky install code for the Windows installer which comprises redistributable packages, and various Qt libraries and plugins.

If you know of a good way to handle various configurations for pack/install in CMake please let us know.

**Comment by rggjan** [comment]
Thanks for the update. Unfortunately, I don't really know of a better / cleaner way to do this with CMake. But if it is as easy as compiling for Debug and copy-pasting the dlls into the package of the release version, maybe adding this as instructions to the README or so would be enough?

**Comment by rggjan** [comment]
I finally came around to trying the mentioned solution

> compile and pack the release version, and copy the (separately compiled) debug dll and lib by hand into the same package

 and it doesn't seem to work. When I do this, it still takes the release version of glbinding, even when I compile the project as "debug" version. I also think its strange that in the built package, I can find a file "glbinding-export.cmake" and "glbinding-export-release.cmake", but no "glbinding-export-debug.cmake".

**Comment by scheibel** [comment]
With the PR https://github.com/cginternals/cmake-init/pull/32 and our update of the cmake-init template in glbinding, this use case should be supported now.

**Comment by rggjan** [comment]
Great to hear, thanks! I'll give it a try...
