### ISSUE TITLE
Question about the existence of v2.0.1 tag

### ISSUE THREAD

**Issue by MiroslavR** [cginternals/glbinding#173]
This is more of a question than an issue. Why is there a tag for 2.0.1? Has 2.0.1 been officially released?

**Comment by scheibel** [comment]
We made the inofficial release 2.0.1 because of our Homebrew formula. I was told the Homebrew maintainer only want tag-based releases in their formula repository and for their pre-built bottles. The difference between 2.0 and 2.0.1 are a fix for OS X console applications (erroneously declared as apps) and a behavior fix for the ```nogl.h``` header (https://github.com/cginternals/glbinding/compare/v2.0.0...v2.0.1).

If you don't work on OS X, 2.0.0 should suffice and if you want to get the latest stuff (including OpenGL API changes) you should stay on our master branch. We really try to not break anything and as far as I remember this is true for the last couple of months.

I hope this answers the question.

**Comment by MiroslavR** [comment]
Thanks, that indeed clears things up!
