### ISSUE TITLE
Provide an interface to query the availability of compound OpenGL extensions and features.

### ISSUE THREAD

**Issue by scheibel** [cginternals/glbinding#174]
It should be easy to query if the current OpenGL driver supports, e.g., OpenGL 4.5.

**Comment by StephanTLavavej** [comment]
I finished converting my program from GLEW to glbinding, and this was the only ability that I had to give up.

**Comment by cgcostume** [comment]
This is partially already provided by the ContextInfo class that can be used e.g.,
```
    std::cout << std::endl
        << "OpenGL Version:  " << ContextInfo::version() << std::endl
        << "OpenGL Vendor:   " << ContextInfo::vendor() << std::endl
        << "OpenGL Renderer: " << ContextInfo::renderer() << std::endl
```
or for extensions:
´``
    const std::set<GLextension> & supportedExts = ContextInfo::extensions(&unknownExts);
    const std::set<GLextension> & allExts = Meta::extensions();
```
Please check out the examples ```glqueries``` and ```glfunctions``` for the use of ```ContextInfo``` in conjunction with ```Meta```.

Can you both please refine this issue and propose additional features that should be covered.

**Comment by cgcostume** [comment]
... in addition, the conversion from GLenum to String and back is supported via ```Meta::getString``` and, e.g., ```Meta::getExtension``` for extensions.

**Comment by scheibel** [comment]
The OpenGL version returned by the ```ContextInfo::version()``` method is the current version of the context. I want a function that takes an OpenGL Feature and manually iterates over all extensions required by this feature and checks for their presence. Then, I want to extend this function to additionally take a list of extensions whose presence is checked, too.

**Comment by cgcostume** [comment]
@scheibel and @StephanTLavavej: Please have a look at the PR #179 and discuss if the added features match your needs.

**Comment by StephanTLavavej** [comment]
It sounds like it would. If I create a core context and ask for the extensions required by 4.5, I'll get a different set than if I create a compatibility context and ask for the extensions required by 4.5, right?

**Comment by cgcostume** [comment]
In both cases you would get the same set of extensions. If a context is core or compatibility does not affect the required extensions to provide this context in the first place. Can you please provide some information on your use case. E.g., if you need the list of functions that are deprecated for a specific core context instead, we can provide this in ```Meta``` as well.

**Comment by StephanTLavavej** [comment]
My use case is simple: I want to know if at runtime I can load every function that's part of the 4.5 core specification, or the 4.2 compatibility specification, etc. so I can be sure that later calls to these functions will all be resolved. If I can't load all of them, I want to know immediately, so I can display a message to the end user.

If the same extensions are required for both core and compatibility flavors of a given OpenGL version, then that makes sense - I thought that some things might be compatibility-only.

**Comment by cgcostume** [comment]
Thanks @StephanTLavavej. I'm going to provide an interface which checks if all functions of a specific opengl version/feature are resolvable. This is currently done already in ```glfunctions``` util, but a common interface in ```ContextInfo``` seems more appropriate.

**Comment by cgcostume** [comment]
@StephanTLavavej We extended ContextInfo and Meta ... to query all unresolved functions potentially required for a specific version ```ContextInfo::supported(...)``` can now be used. Please note that only functions and extensions required directly by the queried version are tested. In order to test all versions below ```Version::preceeding(...)``` can be used to iterate over all earlier versions...

However, it is important to keep in mind, that even if some extensions are not supported or functions cannot be resolved, the associated OpenGL version might be supported by the driver nevertheless (as reported by the driver or resolved on context creation).

For example, the latest intel driver for my integrated Intel 530 enables me to create a 4.4 context even though glbinding reports some extensions, e.g., in 3.1. are missing. This is usually caused by an incomplete/faulty ```gl.xml``` or incomplete driver specification. E.g., ```GL_ARB_texture_buffer_object``` is reported missing since it is not enlisted by the driver, even though the function ```glTexBufferARB``` was successfully resolved. Furthermore, the extension ```GL_ARB_texture_buffer_object_rgb32``` building on top of ```GL_EXT_texture_buffer_object``` (note: ```EXT``` not ```ARB```) is fully supported. This is just one example for a incomplete specification within the ```gl.xml```.

Also: the following functions all typically resolve to different addresses (which does not imply that they are using different implementations...):
* 0x00007FFFFCE8E5D0 glTexBufferEXT
* 0x00007FFFFCE8E5A0 glTexBufferARB
* 0x00007FFFFCE8E570 glTexBuffer 

To wrap this up, i suggest to rely on the provided context version and always explicitly query extensions support for any feature/extension related path in your engine/use-case. With the added glbinding capabilities you can now additionally query if all functions that are required by your rendering are resolved (via version, extension, or manually). I hope this enables you to use glbinding as you would like to. Thanks again.
