### ISSUE TITLE
Bitwise AND and GL_CONTEXT_FLAGS

### ISSUE THREAD

**Issue by Blacklands** [cginternals/glbinding#197]
I'm currently experiencing a small problem with the following code:

```
GLint glFlags;
glGetIntegerv(GLenum::GL_CONTEXT_FLAGS, &glFlags);

if (glFlags & gl::GL_CONTEXT_FLAG_DEBUG_BIT) {

    // Do something.
}
```

As far as I know, the only way to check the context flags that `glGetIntegerv()` returns for a specific bit is by using the & operator, as shown above.

This does not work with glBinding because whatever `gl::ContextFlagMask` is (I guess it is part of an `enum class`?) cannot be AND-ed with either `GLint` nor `GLenum` (the two types the overloads of `glGetIntegerv()` take).

Is there anything I can do about this, something I have missed, or is this a "bug" (more like an oversight I guess)?

**Comment by scheibel** [comment]
There are several coinciding problems here, so I try to summarize my understanding of your code.

You want to perform some code in condition of a specific flag set in a bitfield mask. This bitfield mask is queried from the OpenGL driver.
To test a bit in a bitfield mask you want to use the bitwise *and* operator ```&```. This operator returns a value that you want implicitly cast to bool for the conditional branching.
The query for the bitfield mask (```glGetIntegerv```) currently supports only querying integer values. Unfortunately, glbinding only supports typesafe bitfields (in your case, ```ContextFlagMask```) and unsafe bitfields ```GLbitfield``` which are an unsigned int internally. Additionally, some bitfield values may belong to multiple bitfield types, resulting in our ```SharedBitfield``` template classes.

Further, you try to query a typically type-safe value via an unsafe interface. If you would try to use either a ```GLbitfield``` or a ```ContextFlagMask``` you would experience that glGetIntegerv is not overloaded for these types. Maybe it would be a solution to extend the glGetIntegerv overloads towards all bitfield types.

Then, you want to perform a bitwise and on a GLint and a ```ContextFlagMask``` value. Although this combination of the operator ```&``` can be added, I would strongly advise against this. We can add these operators for unsafe ```GLbitfields``` if you want to use unsafe types in your code.

Last, you want to convert the resulting value to a bool so that the condition is evaluated. Assuming a functioning bitwise *and* operator returning a GLint this would work with standard C++.

Assuming an ideal interface, I would write your code this way:
```cpp
ContextFlagMask glFlags;
glGetIntegerv(GL_CONTEXT_FLAGS, &glFlags);

if (glFlags & GL_CONTEXT_FLAG_DEBUG_BIT) {

    // Do something.
}
```

However, with a reasonable amount of work, I think we could perform something like this:
```cpp
ContextFlagMask glFlags;
glGetIntegerv(GL_CONTEXT_FLAGS, &glFlags);

if ((glFlags & GL_CONTEXT_FLAG_DEBUG_BIT) != GL_NONE_BIT) {

    // Do something.
}
```

And currently possible is this snippet:
```cpp
ContextFlagMask glFlags;
glGetIntegerv(GL_CONTEXT_FLAGS, reinterpret_cast<GLint*>(&glFlags));

if ((glFlags & GL_CONTEXT_FLAG_DEBUG_BIT) != GL_NONE_BIT) {

    // Do something.
}
```
