### ISSUE TITLE
Building of tools cannot be disabled via CMake

### ISSUE THREAD

**Issue by Blacklands** [cginternals/glbinding#213]
I'm currently trying to include glbinding into a project of mine by using CMake.
I have downloaded the current sources (glbinding-master) and put the entire folder into a subfolder for my project.

While everything else is working fine, I now have the problem that I can't seem to find a "clean" way to disable the building of the tools. To disable the tests and examples and so on (since I don't need those either when using glbinding as a library for the project) I just put

```
set(OPTION_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(OPTION_BUILD_GPU_TESTS OFF CACHE BOOL "" FORCE)
set(OPTION_BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(OPTION_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
```

into my CMakeLists.txt, which works well, as expected. However, such an option apparently does not exist for the tools. The CMakeLists.txt in the tools subfolder does not even include any check for a CMake option variable, like the examples and tests etc. do.

Since I am also including GLFW, glbinding finds it during the setup and then attempts to build the tools.
Now of course I can just put an option to disable the tools into the CMakeLists.txt of glBinding myself, and I guess I will do this until another solution emerges.

However, if I'm correct with assessing that there currently is indeed no option to disable the tools, it would be nice if one could be included into the next release. I could do a pull request for this myself if this is desired.

---

Then there is another thing, although not strictly related to this issue, which I want to bring up. Feel free to ignore this if it's not appropriate here:

Before posting this, I briefly tried to get the building of the tools to work (just out of curiosity), but the build in Visual Studio failed because some of the tools include GLFW in their headers, and could not find the GLFW include files during the build.
I then briefly got it to work somehow by putting 

`include_directories (path_to_glfw_includes)`

into my CMakeLists.txt before setting up glbinding in the lines below that, but then the build still failed with LNK1104 because the tools couldn't find glfw3.lib now.
I suspect this is easy to fix if you know your way around with CMake (I don't really, as of now).

While it is not the topic of this issue to find a fix for this, I would like to ask if it's possible to write some more detailed information about how to include glbinding into your own project when using CMake, specifically about taking care of the inter-dependencies with GLFW (and probably also QT and Doxygen I guess). As far as I can see, the readme contains almost nothing about this. 

I'm asking for this mostly because I found that GLFW has [a nice little tutorial for this](http://www.glfw.org/docs/latest/build_guide.html), which really helped me, as a complete CMake newbie, to understand how to include it in my project.
Maybe this is too much to ask for - I don't really know how much work a new section in the readme about this would be, but I assume it would be very low-priority.

**Comment by cgcostume** [comment]
Thanks for your feedback. Concerning the first issue. We are going to revert the ```OPTION_BUILD_TOOLS```.

For including glbinding in any project I generally advise to have glbinding sources not within your project. Instead build and install it somewhere else. E.g., my development stack on Windows is usually on ```C:/dev```. All  my third parties such as glm, glfw, glbinding, and many more are located at ```C:/dev/3rdp```. When i now create a new project, e.g., ```C:/dev/project``` I setup CMakeLists.txt and start CMake via command line, providing the following environment:
```
set _GLM_DIR=C:/dev/3rdp/glm-0.9.8.2
set _GLBINDING_DIR=C:/dev/3rdp/glbinding-2.1.1
set _GLFW_DIR=C:/dev/3rdp/glfw-3.2.1
set CMAKE_PREFIX_PATH=%_GLM_DIR%;%_GLBINDING_DIR%;%_GLFW_DIR%;
set PATH=%_GLFW_DIR%/lib;%_GLBINDING_DIR%;%PATH%;
```
The ```CMAKE_PREFIX_PATH``` allows CMake to automatically find glbinding etc. for my custom project. The ```PATH``` is extended in order to use, e.g., Visual Studio within the same environment (the 3rdp binary directories are therefore added to the path): when starting the application, the glbinding and glfw binaries (in the case of dynamic linking) can be found and the applicatio starts.

There are many many ways to build software. The solution described above I prefer when dealing with a multitude of different projects in Windows, e.g., having 3rdp dependencies in different versions. It prevents mixing up these dependencies due to a clean and unique environment for every project setup.
Having a clean PATH makes it also much easier to test deployment of your project (w.r.t. dependency hell and missing dependencies).

If you have more questions, feel free to ask. Since we aim to use CMake in the most conventional way (which is not defined by any means, so its just our/my opinion) we avoid additional documentation on CMake. Just (1) put glbinding somewhere, (2) provide the path either by GUI oder CLI, and (3) adjust your CMake configuration at appropriate locations using the linking tips: https://github.com/cginternals/glbinding#tips-for-linking.

**Comment by Blacklands** [comment]
Thanks for the quick response (and sorry for the somewhat slow answer)!

Nice to hear that you are going to implement an option for the tools, thank you very much.

Regarding the project installation:

I see your point in linking to glbinding externally instead of providing a copy of it with the project. This is how I work on my own machine preferably, too.

For projects that one is going to deploy somewhere later, I am not sure though. If I didn't totally misunderstand you, you are assuming that other people are either going to download/receive ready-to-run binaries/executables provided by me, or that they are willing to install all the dependencies my project requires to be built and then build it by themselves.

I don't have much experience with this yet, so I'm not sure how feasible providing binaries for all platforms is. I myself tend to rather build libraries I am going to use myself instead of going with precompiled binaries, but that's just me I guess.
Then, if all dependencies of the project in question are included with it, this saves me some work with setting up everything, but it of course also has disadvantages, like the project potentially using outdated versions of the dependencies while I could probably use the newest ones (I guess CMake can't also download the newest versions of dependencies, like for example Gradle can, can it?) if I had to install them myself.

Anyways, thanks a lot for your time on providing this helpful input. I suppose I will try both approaches for now, given that I am partially doing this to get familiar with CMake.

I will leave this issue open for some days in case of possible replies, and then close it, but feel free to close it now already if you want to.
