### ISSUE TITLE
Can't call setCallbackMask without out_of_range exception.

### ISSUE THREAD

**Issue by andrew-kennedy** [cginternals/glbinding#220]
Anytime I attempt to call either setCallbackMask or setCallbackMaskExcept as in the examples, I get this error:
`libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: vector`
I've dug through documentation but can't seem to find any sort of clue as to what could be wrong here. I can use other features of glbinding just fine.

For reference, I'm using glbinding on MacOS Sierra.

**Comment by scheibel** [comment]
Do you use glbinding in release mode so that assertions are disabled?
I assume that the [fetching of the current context](https://github.com/cginternals/glbinding/blob/master/source/glbinding/source/AbstractFunction.cpp#L60) fails. If it is this line, you may have an invalid current context or have failed to tell glbinding the current active context.
For an introduction on context management with glbinding, please refer to our README.md (mostly the [basic setup](https://github.com/cginternals/glbinding/#basic-example) and [advanced context control](https://github.com/cginternals/glbinding/#multi-context-support)).

For further analysis a stacktrace or at least the actual occurence of the assertion failure would be helpful.
Do you have a minimum example that fails?

**Comment by andrew-kennedy** [comment]
Ah man you just beat me to commenting and closing this. I was a complete idiot and didn't realize I was accidentally trying to set the callbacks just before I initialized the bindings. I didn't even think to check because it was too obvious 😑. Thanks for the fast response though!
