### ISSUE TITLE
GLsizeiptr should be defined unsigned?

### ISSUE THREAD

**Issue by dvd0101** [cginternals/glbinding#226]
According to the [spec 4.5](https://khronos.org/registry/OpenGL/specs/gl/glspec45.core.pdf) Table 2.2 (bat you can find the same information on the [wiki](https://www.khronos.org/opengl/wiki/OpenGL_Type)), GLsizeiptr is described as:
> Non-negative binary integer size, for pointer offsets and ranges

It isn't more correct to define GLsizeiptr as an alias of `std::uintptr_t` instead of `ptrdiff_t`?

**Comment by scheibel** [comment]
Probably you're right. But we rely for this declaration on the gl.xml.
The current version (https://github.com/KhronosGroup/OpenGL-Registry/blob/master/xml/gl.xml) states in line 97 that the ```GLsizeiptr``` is a typedef of ```ptrdiff_t```.

**Comment by cinghiale** [comment]
It's a bit inconvenient working with a signed GLsizeiptr that cannot represent a negative value.

Take for example the `glMapBufferRange`; the `length` argument is a `GLsizeiptr` but it cannot be negative otherwise a `GL_INVALID_VALUE` error is returned.

In c++ I'd like to wrap the `glMapBufferRange` in a function that accepts an `uintptr_t` so I can restrict the contract of the function and let the compiler, when invoked with the appropriate command line switches, detects the error.

But since `GLsizeiptr` is signed, this hypothetical function has to check if `length` does not overflow and do something (throw an exception) if it happens.

Said thisI suspect that it is a bit late to patch `gl.xml` since this is the normal behaviour wanted by the specification.

**Comment by scheibel** [comment]
I'll analyze this further, but it is indeed expected by the API and all implementations, the correct abstraction level to handle this is above plain the plain binding.
