### ISSUE TITLE
Access violation reading location 0xFFFFFFFFFFFFFFFF.

### ISSUE THREAD

**Issue by MunWolf** [cginternals/glbinding#238]
I get this access violation exception when I call `glbinding::ContextInfo::vendor()`, it also fails on some other calls like `glbinding::Meta::versions()` or `glbinding::setCallbackMaskExcept(glbinding::CallbackMask::After, { "glGetError" });`

First I initialize glfw,
set these window hints
```
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE);
```
create the window, set the context to current.
call `glbinding::Binding::initialize();`
and check with glGetError if it fails, which it doesn't
then I run this code
```
std::cout << "OpenGL Version:  " << glbinding::ContextInfo::version() << std::endl;
std::cout << "OpenGL Vendor:   " << glbinding::ContextInfo::vendor() << std::endl;
std::cout << "OpenGL Renderer: " << glbinding::ContextInfo::renderer() << std::endl;
std::cout << "OpenGL Revision: " << glbinding::Meta::glRevision() << " (gl.xml)" << std::endl << std::endl;
```
Where it fails on vendor()

Any idea what is going on?

**Comment by scheibel** [comment]
Can you provide additional information about your system? Operating system, graphics card vendor and driver version may help. At a first glance, it may be that context initialization in `glbinding::Binding::initialize` has a defect (e.g., it assumes a reasonable context ID generated by the OS window toolkit). Further, a stack trace may help.

**Comment by jep-dev** [comment]
According to the [specs](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetString.xhtml), "If an error is generated, glGetString returns 0." It doesn't say "if and only if", but I think it's implied, and I don't see how that could result in dereferencing `~0`. I can also see that `glGetError` returns and pops the error, so a check anywhere else could be interfering -
at least `ContextInfo::version` does this. What happens if you perform these reads with GL calls yourself, or re-order the same calls? Do you get the same result with any other window toolkit?

**Comment by scheibel** [comment]
This issue was opened for a past version of glbinding. If this issue still persists in the current master branch or latest release, then please reopen this issue. Closing for now.
