### ISSUE TITLE
Simplify integration into CMake projects

### ISSUE THREAD

**Issue by Anteru** [cginternals/glbinding#239]
I'm trying to use glbinding as part of my source build, and it's really complicated to do so. I've bypassed the compile errors mentioned in #234 by disabling all options and shared libraries. First thing when trying to integrate it into a bigger solution: The options don't have a `GLBINDING` prefix so they are global and may collide with other projects.

Even with everything turned off, the project still produces half a dozen targets. I've tried to specifically include `source/glbinding` but it doesn't build on its own; and it also does a lot of stuff like set up precompiled headers etc. It's close though as it doesn't rely on much stuff and it's reasonably simple to remove the extra stuff. However, it would be great if there's a *simple* CMake project to just build the bindings, without any PCH setup, grouping, extra setup, etc. so I don't have to maintain a custom CMake file :)

**Comment by sbusch42** [comment]
This does not need to be complicated at all. Simply do the following:
1. Download glbinding, put it anywhere you like. Lets say it's located in C:\projects\glbinding. Use cmake to setup the project, build it.
2. Setup your own project using cmake. In it, use
      find_package(glbinding REQUIRED)
      target_link_libraries(${target} glbinding::glbinding)
   Append the path where glbinding is located (i.e., C:\projects\glbinding) to CMAKE_PREFIX_PATH.
   Setup your own project and build it :)

That's all you need to do. You don't even have to install glbinding anywhere (you CAN do that, but you don't need to). CMake will pick up the find script for glbinding and find the project as long as you correctly specified the path with CMAKE_PREFIX_PATH and used the default name for the build directory ("build").

This is exactly the way cmake was designed to work. One project uses another with find_package, by using a find script or a -config.cmake file. I don't understand why so many people seem to think they should include external libraries into their own projects and build them together. This was never intended by cmake (and I use cmake for more than 10 years). If you want to do that, use a superbuild structure based on ExternalProject_Add (see e.g. the cmake mailing list). But in my opinion this only makes things unnecessary complicated.

It only gets complicated when you insist on including one cmake project into another. CMake was never designed for that. And it would never work well, because there is a conflict of interests. As you described, you only want the library. But when you work on a project, you want all the extra targets like tests, examples, install scripts etc. And such a build system will never be easy, considering all the different options needed for multi-platform setups etc. Therefore, it can never work for both sides at the same time.

So, please, simply use cmake projects the way they were supposed to: one build system for one project, and find_package to find and link to external projects. This way all the problems you described do not even occur.
