### ISSUE TITLE
[functions-patches] glGetProgramResource for GLenum

### ISSUE THREAD

**Issue by einsweniger** [cginternals/glbinding#249]
I've noticed you're adding useful typed glGet* functions.
I'd propose you add glGetProgramResource**ev**, since you can query some interfaces [1] for `GL_TYPE`, whereas OpenGL will populate `GLint* params` with various values that should be compared with e.g. `GLenum::GL_FLOAT_VEC4` (c.f. 4.6 Core, p. 114).

That's all, thank you!

[1] BUFFER_VARIABLE, PROGRAM_INPUT, PROGRAM_OUTPUT, TRANSFORM_FEEDBACK_VARYING and UNIFORM (4.6 Core, p. 111)

**Comment by scheibel** [comment]
Thanks for suggesting. I just implemented this feature (b1ddc36b341ef1811e505d0073a6c6f6bd92c4b6), using a function overload of glGetProgramResource**i**v instead of a separate function glGetProgramResource**e**v. This is in accordance to our plan to remove the function patches with explicit type instead of an overloaded function.
