### ISSUE TITLE
Visual Studio 15.5.0 Warnings

### ISSUE THREAD

**Issue by presentfactory** [cginternals/glbinding#250]
I recently updated Visual Studio to the latest version which was released recently (15.5.0) and suddenly glbinding is emitting a good amount of warnings (I think I have it on /W4) from some new deprecation they have added for C++17. The warning is as follows:

```
glbinding\include\glbinding/gl/boolean.h(72): warning C4996:
'std::_Conditionally_enabled_hash<_Kty,true>::result_type': warning STL4007:
Many result_type typedefs and all argument_type, first_argument_type, and second_argument_type typedefs are deprecated in C++17.
You can define _SILENCE_CXX17_ADAPTOR_TYPEDEFS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
```

It also happens in many places in `types.h`.

I don't know how this should be fixed but based on the justification for removing them as can be seen [here](https://stackoverflow.com/a/35907663/2085551), it seems they simply wish a decltype using how the function is called to get its return type or in these cases where the hash is simply returned, `decltype(auto)` or something similar to automatically deduce the return type without using such adaptors.

**Comment by Xirema** [comment]
The way I fixed this issue locally is by adding `-D_SILENCE_CXX17_ADAPTOR_TYPEDEFS_DEPRECATION_WARNING` to the command line of my program. I attached a picture to show where to do that.

You could also add `#define _SILENCE_CXX17_ADAPTOR_TYPEDEFS_DEPRECATION_WARNING` before any `#include` statements that pull in glbinding headers.

This definitely needs to be fixed in the codebase though, since these warnings exist because most major compiler vendors will be dropping large amounts of deprecated behavior in the near future.

![deprecated](https://user-images.githubusercontent.com/1447761/33629483-d0e390e2-d9c9-11e7-936a-57857e058540.PNG)

**Comment by presentfactory** [comment]
Yeah I mean I could define that but the warning might also pop up in my own project somewhere and inform me that I shouldn't be doing that, so I don't like disabling such things. Instead I just find/replaced all instances of the expressions with `result_type` with a regex like `[^\s.]*result_type` or something like that (I forget now) with `decltype(auto)` and that seems to work just fine. I was mainly pointing it out so that it can be fixed as you said.

**Comment by scheibel** [comment]
It seems like the result of a `std::hash<T>::operator()` is unconditionally a `std::size_t`. This should get fixed. Although me may spam `decltype(auto)` throughout our codebase, I suggest we keep C++11 compatibility for now.

**Comment by Tobias1595** [comment]
After the commit above, MSVC 15.7.3 builds the library without any warnings or errors.

**Comment by scheibel** [comment]
Thanks for testing. I'll close this issue for now.
Please comment on this if this problem still remains.
