### ISSUE TITLE
Unable to retrieve Extensions

### ISSUE THREAD

**Issue by Pablode** [cginternals/glbinding#251]
Querying the available extensions using `glbinding::ContextInfo::extensions()` yields an invalid set which I cannot operate on.
This is the only call which does not work - everything else works perfectly. I've encountered this issue on two Windows 10 Systems with the newest VS2017(15.5.2) and both glbinding-2.1.1 (latest binaries) as well as self-built glbinding-2.1.3. The library is properly initialized after context creation and I'm pretty sure everything is right on the CMake-side of the project. SDL2 is providing the context and the error does not occur on Linux (same systems).
Any ideas?

<img width="487" alt="glbinding1" src="https://user-images.githubusercontent.com/3663466/34461565-a9adf828-ee2d-11e7-9dee-18cc5ce17d1d.png">

**Comment by scheibel** [comment]
Thanks for reporting. The underlying issue is that `glGetString` does not allow `GL_EXTENSIONS` as parameter (anymore?), but `glGetStringi` does (source: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetString.xhtml).
I'll provide a fix.

**Comment by scheibel** [comment]
The code we use to query the extensions seems to be correct (for OpenGL 1.0 no extensions, since 1.1 until 3.0 using `glGetString(GL_EXTENSIONS)` and since 3.0 using `glGetInteger(GL_NUM_EXTENSIONS, &count)` and a loop `glGetStringi(GL_EXTENSIONS, i)`.
For each branch in the member function, we return a constructed set.

What OpenGL context is requested and provided by the SDL?

Do you accidentally link glbinding to your project while both use different standard library builds (e.g., one release, one debug)? This return parameter comes from the C++ standard library and is known to have issues when different MSVC DLLs are used.

**Comment by Pablode** [comment]
You're probably right about the linking issue. Just for completeness: an OpenGL 4.0 Context (Core) was requested. However, because of project changes, I'm not in the need to get this working anymore.
Thank you for the quick reply and extensive investigation.
