### ISSUE TITLE
PPA libglbinding-dev conflicts with libegl1-mesa-dev

### ISSUE THREAD

**Issue by Narann** [cginternals/glbinding#299]
Hi and thanks for your hard work!

We use glbinding in decaf emulator. It seems libglbinding 3.1 of cginternals add `/usr/include/KHR/khrplatform.h` which conflict with libegl1-mesa-dev` [ownership](https://packages.debian.org/search?mode=filename&suite=stretch&section=all&searchon=contents&keywords=khrplatform.h).

Making our Travis builds [failing](https://travis-ci.org/decaf-emu/decaf-emu/jobs/525643882):
```
Unpacking libglbinding-dev (3.1.0+571~ubuntu16.04.1) ...
dpkg: error processing archive /var/cache/apt/archives/libglbinding-dev_3.1.0+571~ubuntu16.04.1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/KHR/khrplatform.h', which is also in package libegl1-mesa-dev:amd64 18.0.5-0ubuntu0~16.04.1
```
I'm not a package experts, but because of this `libglbinding` 3.1 is conflicting with `libegl1-mesa-dev` on Xenial.

I suspect you don't want to create a dependency to `libegl1-mesa-dev` because of one single file. Maybe having it in its own dedicated files could be a solution:

```
/usr/include/glbinding/glbinding_khrplatform.h
```

What do you suggest?

Decaf PR for more information [here](https://github.com/decaf-emu/decaf-emu/pull/559).

Have a nice day.

**Comment by scheibel** [comment]
Thanks for reporting and commenting on this issue. We actually added this file for platforms where no EGL headers are as easily available as they are on Ubuntu.
My current suggestion is to fix the deployment and actually use the `libegl1-mesa-dev` dependency on Ubuntu systems. The other solution is to provide the self-provided EGL headers within the directories of glbinding, as you suggested.

**Comment by Narann** [comment]
Thanks for your answer. Are the maintainer of the PPA? Is this place the good one to provide a ticket for PPA modification?

**Comment by scheibel** [comment]
I'm the maintainer for [our PPA](https://launchpad.net/~cginternals/+archive/ubuntu/ppa) and the sources to build the PPA are maintained within the [glbinding repository](https://github.com/cginternals/glbinding/tree/master/deploy/ubuntu-ppa). And if this PPA is actually used by someone other than just us and somebody wanted this to get fixed, well I suppose here is a good place to create tickets for this.

There are other maintainers for the distribution builds of Debian and Ubuntu or even MinGW and Arch, but I think they don't package the newest version of glbinding right now.

**Comment by v1993** [comment]
Is there any progress or plans on this? Wanted to try this library out, met this issue during installation.

**Comment by v1993** [comment]
Until this issue is fixed, you can use this as workaround:

```bash
sudo apt-get -o Dpkg::Options::="--force-overwrite" install libglbinding-dev
```

**Comment by scheibel** [comment]
I updated the glbinding packages in the cginternals PPA for the these Ubuntu versions:
 - Focal (20.04)
 - Eoan (19.10)
 - Disco (19.04)
 - Bionic (18.04)
 - Xenial (16.04)

I verified that the former package could not get installed in my Ubuntu 19.04. With the current published package, the installation runs without error.

However, I noticed one difference. On my system, the suggested package for the KHR includes is `mesa-common-dev`.

**Comment by scheibel** [comment]
I confirmed that the header file in question is indeed located in `libegl1-mesa-dev`.
Compare [list of files in libegl1-mesa-dev](https://packages.ubuntu.com/xenial/arm64/libegl1-mesa-dev/filelist) to [list of files in mesa-common-dev](https://packages.ubuntu.com/xenial/amd64/mesa-common-dev/filelist).

**Comment by v1993** [comment]
@scheibel However, `apt-file find /usr/include/KHR/khrplatform.h` (requires `apt-file` tool) returns `mesa-common-dev: /usr/include/KHR/khrplatform.h` for me on Ubuntu 19.10.

Check [mesa-common-dev filelist in Eoan](https://packages.ubuntu.com/eoan/amd64/mesa-common-dev/filelist) to confirm what I said.

**Comment by scheibel** [comment]
Thanks for the update. We could use different recipes that use `libegl1-mesa-dev` up to bionic and `mesa-common-dev` for the newer versions.

**Comment by hyperboloid77** [comment]
I am also having troubles with glbinding and /usr/include/KHR/khrplatform.h on Ubuntu 20.04 and I wonder if you could help. 

My case is that glbinding installs without errors after adding your ppa, but problems emerge when it gets used/linked in some OpenGL related codes later via cmake:
```
CMake Error at CMakeLists.txt:18 (find_package):
  Found package configuration file:

    /usr/share/glbinding/glbinding-config.cmake

  but it set glbinding_FOUND to FALSE so package "glbinding" is considered to
  be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  glbinding::KHRplatform
```

My configuration is as follows: 

1. "whereis glbinding" yields glbinding: /usr/include/glbinding /usr/share/glbinding
2. apt-file find /usr/include/KHR/khrplatform.h yields libgl-dev: /usr/include/KHR/khrplatform.h
3. sudo find / -name libgl-dev -type d yields  /usr/share/bug/libgl-dev
/usr/share/doc/libgl-dev

The symptom here is that when glbinding installs, it places inside /usr/share/glbinding the file glbinding-config.cmake, which has these lines in the beginning:
```
# List of modules
set(MODULE_NAMES
    KHRplatform
    glbinding
    glbinding-aux
)
```
The module KHRplatform is problematic because unlike in the case of glbinding and glbinding-aux, there is no corresponding subfolder with its corresponding cmake files to be found. Those I can only see on the github's glbinding/3rdparty folder, but it's 3rdparty/KHR, not KHRplatform that is needed inside /usr/share/glbinding once the glbinding package installs on Ubuntu 20.04, and it's not clear for me how to properly copy such files and adjust cmake structures.

It seems there has been the folder KHRplatform inside /usr/share/glbinding at some point in time, which is gone now once you renamed and moved KHR to 3rdparty, yet the glbinding package's cmake files still need it and reference it. 

If I remove KHRplatform from MODULE-NAMES in glbinding-config.cmake then cmake generates properly Makefile, but those type definitions are then missing during the latter compilation.

Any help/comments are welcome.

**Comment by hyperboloid77** [comment]
In case someone has similar difficulties on Ubuntu 20.04, I have solved my problem by cloning glbinding from this git repo by cginternals, changing to that downloaded glbinding folder and then running these commands:
```
mkdir build
cd build
cmake ..
make all
sudo make install

Again, let me repeat that installing glbinding directly from ppa:cginternals/ppa does not work on Ubuntu 20.04 as the resulting glbinding installation is missing the KHRplatform folder with proper cmake files in /usr/share/glbinding.

**Comment by v1993** [comment]
Issue #319 is the same issue as @aabbtree77 described. It's still there as of now.
