### ISSUE TITLE
SDL2 context and glbinding

### ISSUE THREAD

**Issue by damien-lloyd** [cginternals/glbinding#304]
HI there,

I got this bit of code that is producing this error:

`src/Zenhoth/Core/Window.cpp:51:13: error: no matching function for call to 'glbinding::Binding::initialize(Window::Window()::<lambda(const char*)>, bool)'
   51 |     }, false);
      |             ^
In file included from src/Zenhoth/Core/Window.cpp:33:
/usr/include/glbinding/Binding.h:102:17: note: candidate: 'static void glbinding::Binding::initialize(glbinding::GetProcAddress, bool)'
  102 |     static void initialize(glbinding::GetProcAddress functionPointerResolver, bool resolveFunctions = true);
      |                 ^~~~~~~~~~
/usr/include/glbinding/Binding.h:102:54: note:   no known conversion for argument 1 from 'Window::Window()::<lambda(const char*)>' to 'glbinding::GetProcAddress' {aka 'std::function<void (*(const char*))()>'}
  102 |     static void initialize(glbinding::GetProcAddress functionPointerResolver, bool resolveFunctions = true);
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glbinding/Binding.h:121:17: note: candidate: 'static void glbinding::Binding::initialize(glbinding::ContextHandle, glbinding::GetProcAddress, bool, bool)'
  121 |     static void initialize(ContextHandle context, glbinding::GetProcAddress functionPointerResolver, bool useContext = true, bool resolveFunctions = true);
      |                 ^~~~~~~~~~
/usr/include/glbinding/Binding.h:121:77: note:   no known conversion for argument 2 from 'bool' to 'glbinding::GetProcAddress' {aka 'std::function<void (*(const char*))()>'}
  121 |     static void initialize(ContextHandle context, glbinding::GetProcAddress functionPointerResolver, bool useContext = true, bool resolveFunctions = true);
      |                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
`

Here is the offending code:
`
    glbinding::Binding::initialize([](const char * name) {
        return SDL_GL_GetProcAddress(name);
    }, false);
`

I've used `[]` and `[&]` as the capture in the lambda, but still no go. Not quite sure what to do here, since I used to use just `glbinding::Binding::initialize()`.

**Comment by scheibel** [comment]
The problem is that the `glbinding::GetProcAddress` callback type expects a function pointer with no parameters and no return type as return type (`void(*)()`). SDL defines its return type to be a plain `void*`, which is also a valid intermediate type (`reinterpret_casts` are required with either approach).

There are two workarounds I can suggest at this moment:

1. `glbinding::Binding::initialize([](const char * name) { return reinterpret_cast<glbinding::ProcAddress>(SDL_GL_GetProcAddress(name)); }, false);`

2. `glbinding::Binding::initialize(reinterpret_cast<glbinding::ProcAddress(*)(const char*)>(SDL_GL_GetProcAddress), false);`

Can you test these workarounds with your solution?

**Comment by scoult3r** [comment]
The first workaround worked for me.
