### ISSUE TITLE
glbinding-3.1.0 conflicts with libglvnd-1.4.0 (installs files into the same place).  Problematic file: /usr/local/include/KHR/khrplatform.h

### ISSUE THREAD

**Issue by yurivict** [cginternals/glbinding#328]

**Comment by scheibel** [comment]
Thanks for reporting.
I think this issue is somewhat a duplicate or otherwise related to the following issues:
- https://github.com/cginternals/glbinding/issues/299
- https://github.com/cginternals/glbinding/issues/319

Although we're pending on an official release, this behavior should be fixed since https://github.com/cginternals/glbinding/commit/69efa918c74f158bf37aec51489aa9b8aaf047ea and is already integrated when using or other more current development lines `3.2`, `3.3`, and `master`.
You can configure the additional installation of the `KHR/khrplatform.h` header file with the CMake option `OPTION_BUILD_OWN_KHR_HEADERS` (the default is `OFF`).

**Comment by scheibel** [comment]
With the latest release [v3.3.0](https://github.com/cginternals/glbinding/releases/tag/v3.3.0), this should be fixed.
Closing for now.
