### ISSUE TITLE
Passing wglGetProcAddress to glbinding::initialize

### ISSUE THREAD

**Issue by pmakal** [cginternals/glbinding#339]
I guess this is more of a C++ question than glbinding one but... What sort of a cast I need to do to successfully pass `wglGetProcAddress` to `glbinding::initialize` function?

Related to this topic:

- Since it is possible to just pass `nullptr` to initialization function, and it seems to resolve it self without problems, what are the downsides of such an approach? Passing `nullptr` would lead to invoking `glbinding::getProcAddress` which code documentation states that is should not be used. Why is that?
- To add to previous point: since it is not recommended to use `getProcAddress`, could glbinding example on main project page in section "Multi-Threading Support" be updated to not use it?

**Comment by scheibel** [comment]
In order to pass `wglGetProcAddress` to `glbinding::initialize`, you'll have to perform a `reinterpret_cast`.
This can look somethink like this:
```cpp
glbinding::Binding::initialize([](const char * name) {
        return reinterpret_cast<glbinding::ProcAddress>(wglGetProcAddress(name));
    }, false);
```
However, and i think this should be more prominent in the documentation, `wglGetProcAddress` is not an actual replacement for `glbinding::getProcAddress` or actual recommended functions from your windowing toolkit (Qt, glfw3, see https://github.com/cginternals/glbinding/blob/master/source/examples/cubescape-qt/Canvas.cpp#L279 and https://github.com/cginternals/glbinding/blob/master/source/examples/cubescape/main.cpp#L99).
With this cast, you can use `wglGetProcAddress` to resolve OpenGL function names on Windows, but unfortunately, it doesn't handle all of them. For more details, see the Khronos OpenGL Wiki: https://www.khronos.org/opengl/wiki/Load_OpenGL_Functions#Windows

The main point why we discourage the use of `glbinding::getProcAddress` is the internal use of native APIs that we want to get rid of. Also, we don't want to support special behavior in function resolution, especially as it is already implemented in windowing toolkits sich as Qt and glfw3.

**Comment by pmakal** [comment]
Thank you for clarification!
